## Import the relevant libraries

In [1]:
import numpy as np

## Declaring scalars, vectors and matrices

### Scalars

In [2]:
s=5
s

5

### Vectors

In [3]:
v=np.array([5,-2,4])
v

array([ 5, -2,  4])

### Matrices

In [8]:
m=np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [13]:
s_array=np.array(5)
s_array

array(5)

In [14]:
type(s_array)

numpy.ndarray

### Data shapes

In [15]:
m.shape

(2, 3)

In [16]:
v.shape

(3,)

### Creating a column vector

In [17]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

### Creating a tensor

In [19]:
m1=np.array([[5,12,6],[-3,0,14]])
m2=np.array([[9,8,7],[1,3,-5]])

In [20]:
t=np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Checking its shape

In [21]:
t.shape

(2, 2, 3)

### Manually creating a tensor

In [22]:
t_manual=np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

In [23]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Addition

In [24]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Difference

In [25]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Transposing matrices

In [26]:
A=np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [28]:
B=np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [29]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [30]:
C=np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [31]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing vectors

In [32]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [33]:
x.T

array([1, 2, 3])

In [34]:
x.shape

(3,)

In [35]:
x_reshaped=x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [36]:
x_reshaped.T

array([[1],
       [2],
       [3]])

### Dot product

In [39]:
x=np.array([2,8,-4])
y=np.array([1,-7,3])
np.dot(x,y)

-66

In [40]:
u=np.array([0,2,5,8])
v=np.array([20,3,4,-1])
np.dot(u,v)

18

### Scalar * Scalar

In [41]:
np.dot(5,6)

30

### Scalar * vector

In [42]:
5*x

array([ 10,  40, -20])

### Scalar * Matrix

In [43]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [44]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix * matrix

Condition: we can only multiply an mxn matrix with an nxk matrix. The output is an mxk matrix.

In [46]:
B=np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [47]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])